import express from "express";
import { GoogleGenAI } from "@google/genai";
import { pool } from "../db.js";
import { authMiddleware } from "../middleware/auth.middleware.js";

const router = express.Router();

router.post("/generate", authMiddleware, async (req, res) => {
  const { prompt } = req.body;
  const userId = req.user.id;

  if (!prompt) {
    return res.status(400).json({ message: "Prompt tidak boleh kosong" });
  }

  if (!process.env.GEMINI_API_KEY) {
    return res.status(500).json({ message: "Konfigurasi server error: GEMINI_API_KEY belum disetel" });
  }

  try {
    const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

    // Instruksi sistem yang ketat untuk mengembalikan JSON schema yang kita inginkan
    const systemPrompt = `Kamu adalah AI Travel Assistant ahli. 
Tugasmu adalah membuat rencana perjalanan (itinerary) lengkap berdasarkan input user.
PENTING: Kamu HANYA BOLEH membalas dengan format JSON valid TANPA markdown code block (jangan gunakan \`\`\`json), langsung mulai dengan tanda kurung kurawal { dan akhiri dengan }.

Format JSON yang diwajibkan:
{
  "name": "Nama Trip (misal: Liburan ke Tokyo)",
  "destination": "Nama Kota/Negara",
  "notes": "Deskripsi singkat mengenai trip ini",
  "total_budget": 5000000,
  "days": [
    {
      "dayNumber": 1,
      "items": [
        {
          "title": "Nama aktivitas",
          "locationName": "Lokasi spesifik yang bisa dicari di Google Maps",
          "startTime": "08:00",
          "endTime": "10:00",
          "activityType": "sightseeing",
          "notes": "Catatan ringkas"
        }
      ]
    }
  ],
  "expenses": [
    {
      "category": "flight",
      "title": "Tiket Pesawat",
      "amount": 2000000
    }
  ]
}

Aturan aktivitas: activityType hanya boleh bernilai "sightseeing", "dining", "cafe", "hotel", "flight", atau "other".
Pastikan jam (startTime/endTime) berurutan dari pagi ke malam dalam satu hari.
Pastikan total expenses tidak melebihi budget (jika user memberikan budget).
Pastikan destinasi yang direkomendasikan masuk akal (lokasi saling berdekatan dalam satu area/kota jika di hari yang sama).`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        systemInstruction: systemPrompt,
        temperature: 0.7,
        responseMimeType: "application/json"
      }
    });

    const jsonText = response.text;
    
    let tripData;
    try {
      tripData = JSON.parse(jsonText);
    } catch (parseError) {
      console.error("Failed to parse AI JSON:", jsonText);
      return res.status(500).json({ message: "Gagal memproses hasil dari AI. AI mengembalikan format yang salah." });
    }

    // Helper to format time safely
    const formatTime = (t) => {
      if (!t) return null;
      const str = String(t).trim();
      if (/^\d{2}:\d{2}:\d{2}$/.test(str)) return str;
      if (/^\d{2}:\d{2}$/.test(str)) return `${str}:00`;
      const match = str.match(/(\d{1,2}):(\d{2})/);
      if (match) {
        return `${match[1].padStart(2, '0')}:${match[2]}:00`;
      }
      return null;
    };

    // Hitung start_date (hari ini) dan end_date (hari ini + (total hari - 1))
    const startDate = new Date();
    const endDate = new Date(startDate);
    const totalDays = tripData.days && Array.isArray(tripData.days) ? tripData.days.length : 1;
    endDate.setDate(startDate.getDate() + Math.max(0, totalDays - 1));

    // Mulai Transaksi Database (Simpan seluruh hasil AI)
    const connection = await pool.getConnection();
    await connection.beginTransaction();

    try {
      const tripName = tripData.name || "AI Generated Trip";
      const tripDest = tripData.destination || "Berbagai Destinasi";

      // 1. Insert Trip
      const [tripResult] = await connection.execute(
        `INSERT INTO trips (user_id, name, destination, start_date, end_date, notes) VALUES (?, ?, ?, ?, ?, ?)`,
        [userId, tripName, tripDest, startDate, endDate, tripData.notes || "Auto-generated by AI"]
      );
      const newTripId = tripResult.insertId;

      // 2. Insert Budget
      if (tripData.total_budget) {
        const budgetAmount = parseFloat(String(tripData.total_budget).replace(/[^\d.-]/g, ''));
        if (!isNaN(budgetAmount)) {
          await connection.execute(
            `INSERT INTO budgets (trip_id, total_budget, currency) VALUES (?, ?, ?)`,
            [newTripId, budgetAmount, "IDR"]
          );
        }
      }

      // 3. Insert Expenses
      if (tripData.expenses && Array.isArray(tripData.expenses)) {
        for (const exp of tripData.expenses) {
          // Normalisasi kategori
          const validCategories = ['transport', 'hotel', 'food', 'ticket', 'other'];
          const cat = validCategories.includes(exp.category) ? exp.category : 'other';
          const expAmount = parseFloat(String(exp.amount).replace(/[^\d.-]/g, ''));
          
          if (!isNaN(expAmount)) {
            await connection.execute(
              `INSERT INTO expenses (trip_id, category, title, amount, expense_date) VALUES (?, ?, ?, ?, ?)`,
              [newTripId, cat, exp.title || "Pengeluaran", expAmount, startDate]
            );
          }
        }
      }

      // 4. Insert Days and Items
      if (tripData.days && Array.isArray(tripData.days)) {
        for (const day of tripData.days) {
          const currentDate = new Date(startDate);
          currentDate.setDate(startDate.getDate() + ((day.dayNumber || 1) - 1));

          const [dayResult] = await connection.execute(
            `INSERT INTO itinerary_days (trip_id, day_number, date) VALUES (?, ?, ?)`,
            [newTripId, day.dayNumber || 1, currentDate]
          );
          const newDayId = dayResult.insertId;

          if (day.items && Array.isArray(day.items)) {
            let sortOrder = 1;
            for (const item of day.items) {
              const actType = item.activityType || 'sightseeing';
              const fStart = formatTime(item.startTime);
              const fEnd = formatTime(item.endTime);
              
              await connection.execute(
                `INSERT INTO itinerary_items (itinerary_day_id, title, location_name, start_time, end_time, activity_type, notes, sort_order)
                 VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
                [
                  newDayId, 
                  item.title || "Aktivitas", 
                  item.locationName || null, 
                  fStart, 
                  fEnd, 
                  actType, 
                  item.notes || null, 
                  sortOrder
                ]
              );
              sortOrder++;
            }
          }
        }
      }

      await connection.commit();
      connection.release();

      return res.status(201).json({
        message: "Trip berhasil di-generate",
        tripId: newTripId,
        tripName: tripName
      });
    } catch (dbError) {
      await connection.rollback();
      connection.release();
      console.error("Database Transaction Error:", dbError);
      throw dbError;
    }
  } catch (error) {
    console.error("AI Generation Error:", error);
    
    // Handle specific Gemini API errors
    if (error.status === 503 || error.message?.includes("high demand") || error.message?.includes("UNAVAILABLE")) {
      return res.status(503).json({ message: "Server AI (Gemini) sedang mengalami beban tinggi (High Demand). Silakan coba klik tombol Generate sekali lagi." });
    }
    
    res.status(500).json({ message: "Gagal men-generate itinerary dengan AI. Silakan coba prompt yang lebih spesifik." });
  }
});

export default router;
